services:
  mysql:
    image: mysql:8.0
    env_file: .env
    container_name: ninja_mysql
    hostname: mysql

    ports:
      - '3307:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  ninja:
    build: ./ninja
    container_name: ninja
    hostname: ninja
    env_file: ./ninja/.env
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - internal

  ninja_gateway:
    build: ./ninjaGateway
    container_name: ninja_gateway
    hostname: ninja_gateway
    env_file: ./ninjaGateway/.env
    ports:
      - '8085:8085'
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
